### ISSUE TITLE
All your links to YunoHost don't work

### ISSUE THREAD

**Issue by Perlover** [YunoHost-Apps/satdress_ynh#2]
Bottom link: https://yunohost.org/app_satdress

Button link: https://install-app.yunohost.org/?app=satdress

These links are not work (Page not found)

**Comment by tituspijean** [comment]
> Bottom link: [yunohost.org/app_satdress](https://yunohost.org/app_satdress)

Any contribution is welcome, as stated in the linked page. :)

> Button link: [install-app.yunohost.org/?app=satdress](https://install-app.yunohost.org/?app=satdress)

This will be automatically solved once our catalog is updated.

---

Note that the package is not finished yet, too.

**Comment by navanchauhan** [comment]
Closing as the app is now in the catalog
